# Generated by Django 2.2.28 on 2024-08-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
